### PR TITLE
TMDb Importing

### LINKED ISSUE #215: Support TMDB/IMDB importing

### PR DESCRIPTION
**Pull request by IRHM**
Add support for importing from TMDb watched list csv export.

Related #214

Closes #215

### CODE REVIEW

**Comment by MathieuMoalic** [comment]
Nice one, you found a much cleaner solution than what I could do :) . I do have a couple questions though, when I try to import, it doesn't keep the ratings, is it a bug or intended?

**Comment by IRHM** [comment]
> Nice one, you found a much cleaner solution than what I could do :) . I do have a couple questions though, when I try to import, it doesn't keep the ratings, is it a bug or intended?

Oh I didnt implement saving ratings.

When I was testing creating a list on tmdb, for some reason when I gave something a rating it would be removed from my list.

I see now that your example data (https://github.com/sbondCo/Watcharr/issues/130#issuecomment-1795856431) has a YourRating.

I think I saw you could add notes to movies too, but that seems to be on custom lists you cant export on tmdb. So I guess we cant do that to save `thoughts` too.

I'll have a look at adding the ratings, should be an ezpz fix (hopefully).

**Comment by MathieuMoalic** [comment]
Also, the data includes the date of the rating, I think it would be cool not to lose that as well.

**Comment by IRHM** [comment]
> Also, the data includes the date of the rating, I think it would be cool not to lose that as well.

Hey, just released [v1.25.0](https://github.com/sbondCo/Watcharr/releases/tag/v1.25.0) with this functionality.

Changing the date of an activity is a planned feature so I was able to get some of that work done in the backend for saving the original rating date.

It'll look something like this after importing (bottom activity says "Original Rating on TMDb" - my screenshot tool buggy :disappointed:):

image


Let me know if anything else comes up!

**Pull request merged**
